version: '3'
services:
  web:
    container_name: mccs
    build:
      context: .
      dockerfile: dockerfile.production
      args:
        - GIT_TAG=$GIT_TAG
        - BUILD_DATE=$BUILD_DATE
        - GIT_COMMIT=$GIT_COMMIT
        - GIT_TREE_STATUS=$GIT_TREE_STATUS
    restart: always
    volumes:
      - ./:/usr/src/app
    ports:
      - 8080:8080
    depends_on:
      - postgres
      - mongo
      - redis
      - es01

  postgres:
    container_name: postgres
    image: postgres:11.15
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_DB=mccs
    volumes:
      - postgresql:/var/lib/postgresql/data

  mongo:
    container_name: mongo
    image: mongo:4.2.18
    restart: always
    ports:
      - 27017:27017
    volumes:
      - mongodb:/data/db
      - restore:/data/restore

  es01:
    container_name: es01
    image: docker.elastic.co/elasticsearch/elasticsearch:7.16.2
    restart: always
    environment:
      - node.name=es01
      - cluster.initial_master_nodes=es01
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - "xpack.security.enabled=false"
    ports:
      - 9200:9200
    volumes:
      - esdata01:/usr/share/elasticsearch/data

  kibana:
    container_name: kibana
    image: docker.elastic.co/kibana/kibana:7.16.2
    restart: always
    environment:
      - ELASTICSEARCH_HOSTS=http://es01:9200
    ports:
      - 5601:5601
    depends_on:
      - es01

volumes:
  mongodb:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: 'mnt/mccs_data/mongo'
  esdata01:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: 'mnt/mccs_data/es'
  restore:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: 'mnt/mccs_data/restore'
  postgresql:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: 'mnt/mccs_data/postgres'
